language: minimal
dist: focal
sudo: required
services:
  - docker
before_install:
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.6.1/buildx-v0.6.1.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  - docker run --privileged --rm tonistiigi/binfmt --install arm64
before_script:
  - tag="${TRAVIS_TAG:-latest}"
  - image_name="$(echo "${TRAVIS_REPO_SLUG}" | cut -d '/' -f 2)"
  - docker_org="actions"
  - docker buildx create --use
script:
  - docker buildx build --tag ${docker_org}/${image_name}:${tag} --platform linux/amd64,linux/arm64 .
before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  - provider: script
    script: docker buildx build --push --tag ${docker_org}/${image_name}:${tag} --platform linux/amd64,linux/arm64 .
    on:
      branch: master
  - provider: script
    script: docker buildx build --push --tag ${docker_org}/${image_name}:${tag} --platform linux/amd64,linux/arm64 .
    on:
      branch: master
      tags: true